apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic
  namespace: managed-gbenhaim-app
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: appstudio
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: devfile-sample-go-basic
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: devfile-sample-go-basic-
      labels:
        build.appstudio.openshift.io/application: appstudio
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: devfile-sample-go-basic
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: managed-gbenhaim-app
    spec:
      params:
      - name: git-url
        value: https://github.com/gbenhaim/devfile-sample-go-basic
      - name: output-image
        value: quay.io/productcicd/hacbs-apps:managed-gbenhaim-app-devfile-sample-go-basic-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: devfile-sample-go-basic/$(tt.params.git-revision)
    status: {}
status: {}
